### ISSUE TITLE
Trying with E8372h-320 (CL4E8372HM01)

### ISSUE THREAD

**Issue by evert-arias** [vzakharchenko/huawei-hilink#1]
Apparently the authentication method is not the same in this model. If anyone knows something about it, I would like to hear it, anyway I will be publishing here any progress I have.
![Screenshot_1](https://user-images.githubusercontent.com/30301607/140822333-062b4994-effc-4c28-97f5-5a57d4f4e536.png)

**Comment by evert-arias** [comment]
This is the error code I am getting when I try to access anything that needs authentication.
![error-code-100003](https://user-images.githubusercontent.com/30301607/140822384-55fd1f6e-3f08-48fb-9019-1583d8099f57.png)

**Comment by vzakharchenko** [comment]
@evert-arias ,
Can you  try run with parameter ```--rsapaddingtype="0"```

**Comment by evert-arias** [comment]
@vzakharchenko I tried with parameter `--rsapaddingtype="0"` and it makes no difference.

**Comment by wokrucinski** [comment]
same issue for me, even with parameter:

Error: Delete message error: {"error":{"code":["100003"],"message":[""]}}
    at /usr/local/lib/node_modules/huawei-hilink/src/ListSMS.js:165:19
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/huawei-hilink/src/ListSMS.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)

**Comment by rebelboy** [comment]
huawei.publicKey.rsapadingtype=1
e8372 is ok

**Comment by GregoryW21** [comment]
I got error with {"error":{"code":["100003"],"message":[""]}} 
my one is B311, but using wireshark, the api is also using /api/sms/send-api
I have already login successfully and can get "publicKey" from /api/user/authentication_login
however, still got 100003 error after sendsms

Anyone have new update?

**Comment by Sami2324** [comment]
Hi treve, I been trying for months and haven't been able to firmware unlock my E8372h-320 wingle and now I am fed up of it as it's no use to me locked. Please if you could use your expertise here and help me unlock it, I will be really grateful. 

I have tried contacting Huawei support and other forums but they were unwilling to help due to their "rules" and just tossed my case around.
